// <auto-generated />
namespace ParkingCore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class v9 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v9));
        
        string IMigrationMetadata.Id
        {
            get { return "202206110940481_v9"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
